doctrine:
  dbal:
  orm:
    mappings:
      banners:
         type: annotation
         is_bundle: false
         dir: "%kernel.project_dir%/src/Backend/Modules/EnerBanners/Domain/Banners"
         alias: Banners
         prefix: Backend\Modules\EnerBanners\Domain\Banners